### ISSUE TITLE
Salery pay slip need to be sorted

### ISSUE THREAD

**Issue by mdzahid-pro** [Sharifur/xTeam-app#2]
Salery pay slip need to be sorted and desc order

**Comment by KamrulIbnZaman** [comment]
Hi [mdzahid-pro](https://github.com/mdzahid-pro),

Thank you for creating a new issue on our xTeam-app repository on GitHub. We appreciate your engagement with our project!

Our team will review the issue as soon as possible and provide the necessary attention. If you could kindly provide more details or context about the issue you’re facing, it would greatly assist us in addressing it effectively.

We’ll keep you updated on the progress and any discussions related to this issue. If you have any further questions or need immediate assistance, please feel free to reach out.

Thanks again for your contribution to our project.

Best regards,
Kamrul Ibn Zaman
Mobile App Developer, Xgenious
[Kamrulibnzaman@gmail.com](mailto:Kamrulibnzaman@gmail.com)

**Comment by KamrulIbnZaman** [comment]
Hi [mdzahid-pro](https://github.com/mdzahid-pro),

Thank you for creating a new issue on our xTeam-app repository on GitHub. We appreciate your engagement with our project!

Our team will review the issue as soon as possible and provide the necessary attention. If you could kindly provide more details or context about the issue you’re facing, it would greatly assist us in addressing it effectively.

We’ll keep you updated on the progress and any discussions related to this issue. If you have any further questions or need immediate assistance, please feel free to reach out.

Thanks again for your contribution to our project.

Best regards,
Kamrul Ibn Zaman
Mobile App Developer, Xgenious
[Kamrulibnzaman@gmail.com](mailto:Kamrulibnzaman@gmail.com)

**Comment by KamrulIbnZaman** [comment]
you issue has been solved..

**Comment by mdzahid-pro** [comment]
I have checked this issue 

and I have found this issue again very sad you're clamming issue has been solved but it exist

**Comment by KamrulIbnZaman** [comment]
It's a server issue. from future data this list will be okay, but for the previous data we are unable to solve the previous data sorting issue.
